name: Generate Octocat Walker

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite
  workflow_dispatch:       # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Octocat walker
        uses: YihanWu/octocat-commits@main
        with:
          user_name: apoltronieri   
          theme: github-dark        # opções: github-dark, github-light
          output_path: ./octocat.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
